# Generated by Django 4.1.4 on 2023-06-07 14:21

from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('prenom', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('date_naissance', django_cryptography.fields.encrypt(models.DateTimeField(max_length=50))),
                ('mail', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('telephone', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
                ('adresse', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('code_postal', django_cryptography.fields.encrypt(models.CharField(max_length=5))),
                ('date_inscription', django_cryptography.fields.encrypt(models.DateTimeField(max_length=50))),
                ('fiche_inscription', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('certificat_medical', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('date_certificat', django_cryptography.fields.encrypt(models.DateTimeField(max_length=50, null=True))),
                ('autorisation_parentale', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('photo', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('affiche_trombinoscope', django_cryptography.fields.encrypt(models.BooleanField(null=True))),
                ('affiche_annuaire', django_cryptography.fields.encrypt(models.BooleanField(null=True))),
                ('date_desinscription', django_cryptography.fields.encrypt(models.DateTimeField(max_length=50))),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('prenom', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('date_naissance', django_cryptography.fields.encrypt(models.DateTimeField(max_length=50))),
                ('mail', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('telephone', django_cryptography.fields.encrypt(models.CharField(max_length=20))),
                ('adresse', django_cryptography.fields.encrypt(models.CharField(max_length=50))),
                ('code_postal', django_cryptography.fields.encrypt(models.CharField(max_length=5))),
                ('date_inscription', django_cryptography.fields.encrypt(models.DateTimeField(max_length=50))),
                ('fiche_inscription', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('certificat_medical', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('date_certificat', django_cryptography.fields.encrypt(models.DateTimeField(max_length=50, null=True))),
                ('autorisation_parentale', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('photo', django_cryptography.fields.encrypt(models.ImageField(null=True, upload_to=''))),
                ('affiche_trombinoscope', django_cryptography.fields.encrypt(models.BooleanField(null=True))),
                ('affiche_annuaire', django_cryptography.fields.encrypt(models.BooleanField(null=True))),
            ],
        ),
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=50)),
                ('idAdherent', models.ManyToManyField(to='inscription.inscription')),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=50)),
                ('idAdherent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.inscription')),
            ],
        ),
    ]
