# Generated by Django 4.1.4 on 2023-06-08 08:46

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0003_inscription_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='login_count',
            field=django_cryptography.fields.encrypt(models.IntegerField(default=0, null=True)),
        ),
    ]
