# Generated by Django 4.1.3 on 2023-06-09 06:35

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0004_alter_inscription_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='Cotisation',
            field=django_cryptography.fields.encrypt(models.BooleanField(null=True)),
        ),
    ]
