# Generated by Django 4.1.4 on 2023-06-06 10:37

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0007_alter_inscription_code_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='affiche_annuaire',
            field=django_cryptography.fields.encrypt(models.BooleanField(null=True)),
        ),
        migrations.AddField(
            model_name='inscription',
            name='affiche_trombinoscope',
            field=django_cryptography.fields.encrypt(models.BooleanField(null=True)),
        ),
    ]
