# Generated by Django 4.1.4 on 2023-06-06 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inscription', '0009_alter_inscription_date_certificat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='idAdherent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inscription.inscription'),
        ),
        migrations.AlterField(
            model_name='statut',
            name='idAdherent',
            field=models.ManyToManyField(to='inscription.inscription'),
        ),
        migrations.DeleteModel(
            name='Adherents',
        ),
    ]
